# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimDisc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(help_text='Enter the primary discipline.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecDisc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary', models.CharField(help_text='Enter the secondary discipline.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolnum', models.CharField(max_length=100)),
                ('toolname', models.CharField(max_length=200)),
                ('tooldraw', models.CharField(blank=True, max_length=200)),
                ('dcatid', models.CharField(blank=True, max_length=100)),
                ('pcatid', models.CharField(blank=True, max_length=100)),
                ('toolnotes', models.TextField(blank=True, help_text='Enter any notes for this tool as necessary', max_length=1000)),
                ('primdisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PrimDisc')),
                ('secdisc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SecDisc')),
            ],
        ),
    ]
