# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170823_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdisc',
            name='secondary',
            field=models.CharField(blank=True, help_text='Enter the secondary discipline.', max_length=100),
        ),
    ]
