# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170823_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdisc',
            name='secondary',
            field=models.CharField(blank=True, help_text='Enter the secondary discipline.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pcatid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
