# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170823_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdisc',
            name='secondary',
            field=models.CharField(help_text='Enter the secondary discipline.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='secdisc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SecDisc'),
        ),
    ]
