# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170823_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='dcatid',
            field=models.CharField(blank=True, max_length=100, verbose_name='DNGS CatID'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='draw',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tool Drawing(s)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tool Name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='num',
            field=models.CharField(max_length=100, verbose_name='Tool No.'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pcatid',
            field=models.CharField(blank=True, max_length=100, verbose_name='PNGS CatID'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='primdisc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PrimDisc', verbose_name='Primary Discipline'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='secdisc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SecDisc', verbose_name='Secondary Discipline'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='pm',
            field=models.CharField(choices=[('c', 'complete'), ('i', 'incomplete')], help_text='Is PM complete for this tool?', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='sn',
            field=models.CharField(max_length=10, verbose_name='Tool SN'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tool', verbose_name='Tool No.'),
        ),
    ]
