# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170823_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primdisc',
            options={'ordering': ['primary']},
        ),
        migrations.AlterModelOptions(
            name='secdisc',
            options={'ordering': ['secondary']},
        ),
    ]
