# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170823_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='toolpic',
        ),
    ]
