# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_tool_toolpic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['primdisc', 'num'], 'verbose_name': 'Tool'},
        ),
        migrations.AlterModelOptions(
            name='toolsn',
            options={'ordering': ['tool', 'sn'], 'verbose_name': 'Tool SN'},
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='pm',
            field=models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], help_text='Is PM complete for this tool?', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='repair',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], help_text='Does this tool need to be repaired?', max_length=5),
        ),
    ]
