# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_toolsn_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsn',
            options={'ordering': ['tool', 'sn'], 'permissions': (('can_mark_returned', 'set book as returned'),), 'verbose_name': 'Tool SN'},
        ),
    ]
