# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170828_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(help_text='Enter tool location.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='primdisc',
            name='primary',
            field=models.CharField(help_text='Enter the primary discipline.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='secdisc',
            name='secondary',
            field=models.CharField(blank=True, help_text='Enter the secondary discipline.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='num',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tool No.'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='checkdate',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
