# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170830_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primdisc',
            options={'ordering': ['id'], 'verbose_name': 'Primary Discipline'},
        ),
        migrations.AlterModelOptions(
            name='secdisc',
            options={'ordering': ['id'], 'verbose_name': 'Secondary Discipline'},
        ),
    ]
