# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20170905_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location'], 'permissions': (('can_add_location', 'add location'),)},
        ),
    ]
