# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20170907_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location'], 'permissions': (('can_add_location', 'Can add location'),)},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['primdisc', 'num'], 'permissions': (('can_edit_tool', 'Can edit Tool'),), 'verbose_name': 'Tool'},
        ),
    ]
