# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20170907_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsn',
            name='vault',
            field=models.CharField(blank=True, choices=[('In', 'In'), ('Out', 'Out')], help_text='Is this tool IN or OUT of the vault?', max_length=5, null=True),
        ),
    ]
