# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0022_toolsn_vault'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalToolSN',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique ID for tool')),
                ('sn', models.CharField(max_length=10, verbose_name='Tool SN')),
                ('pm', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is PM complete for this tool?', max_length=50)),
                ('repair', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Does this tool need to be repaired?', max_length=5)),
                ('checkdate', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('comments', models.TextField(blank=True, help_text='Enter any comments for this tool as necessary.', max_length=1000)),
                ('vault', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], help_text='Is this tool IN or OUT of the vault?', max_length=5, verbose_name='Vault Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('borrower', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.Location')),
                ('tool', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.Tool')),
            ],
            options={
                'verbose_name': 'historical Tool SN',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='vault',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], help_text='Is this tool IN or OUT of the vault?', max_length=5, verbose_name='Vault Status'),
        ),
    ]
