# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20170914_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoolsn',
            name='vaulttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 14, 10, 9, 19, 982803), null=True),
        ),
        migrations.AddField(
            model_name='toolsn',
            name='vaulttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 14, 10, 9, 19, 982803), null=True),
        ),
    ]
