# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20170914_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoolsn',
            name='vaulttime',
        ),
        migrations.RemoveField(
            model_name='toolsn',
            name='vaulttime',
        ),
        migrations.AddField(
            model_name='historicaltoolsn',
            name='vaultintime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vault In Time'),
        ),
        migrations.AddField(
            model_name='historicaltoolsn',
            name='vaultouttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vault Out Time'),
        ),
        migrations.AddField(
            model_name='toolsn',
            name='vaultintime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vault In Time'),
        ),
        migrations.AddField(
            model_name='toolsn',
            name='vaultouttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vault Out Time'),
        ),
    ]
