# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20170914_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsn',
            options={'ordering': ['tool', 'sn'], 'permissions': (('can_mark_returned', 'set book as returned'), ('can_log_vault', 'change vault status for tools')), 'verbose_name': 'Tool SN'},
        ),
    ]
