# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20180123_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='minneeded',
            field=models.IntegerField(default='0', verbose_name='Minimum Tools Requiried'),
        ),
    ]
