# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_tool_minneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltoolsn',
            name='pm',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is PM complete for this tool?', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltoolsn',
            name='repair',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Does this tool need to be repaired?', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicaltoolsn',
            name='vault',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is this tool in the vault?', max_length=5, verbose_name='Stores in vault'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='pm',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is PM complete for this tool?', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='repair',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Does this tool need to be repaired?', max_length=5),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='vault',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is this tool in the vault?', max_length=5, verbose_name='Stores in vault'),
        ),
    ]
