# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_job_jobtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank='True', help_text='Any comments that would help find this location.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Enter tool location.', max_length=200, unique=True, verbose_name='Location Name'),
        ),
    ]
