# Generated by Django 2.0.1 on 2018-01-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20180130_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultlog',
            options={'get_latest_by': 'borrowdate', 'verbose_name': 'Tool Vault Log'},
        ),
    ]
