# Generated by Django 2.0.1 on 2018-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_vaultlog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultlog',
            name='isreturned',
            field=models.BooleanField(default='0', verbose_name='has tool been returned'),
        ),
    ]
