# Generated by Django 2.0.1 on 2018-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20180131_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlog',
            name='isreturned',
            field=models.BooleanField(default='0', verbose_name='is the tool returned?'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='why was tool taken out'),
        ),
    ]
