# Generated by Django 2.0.1 on 2018-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20180131_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultlog',
            name='invault',
        ),
        migrations.AddField(
            model_name='vaultlog',
            name='action',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='Out', max_length=2, verbose_name='action on the tool'),
        ),
    ]
