# Generated by Django 2.0.1 on 2018-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20180131_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowlog',
            options={'get_latest_by': ('borrowdate', 'id'), 'ordering': ('-time', 'id'), 'verbose_name': 'Tool Vault Log'},
        ),
        migrations.AlterModelOptions(
            name='vaultlog',
            options={'get_latest_by': ('time', 'id'), 'ordering': ('-time', 'id'), 'verbose_name': 'Tool Vault Log'},
        ),
        migrations.AlterField(
            model_name='vaultlog',
            name='action',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='out', max_length=3, verbose_name='action on the tool'),
        ),
    ]
