# Generated by Django 2.0.1 on 2018-01-31 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20180131_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlog',
            name='approvedby',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_log', to=settings.AUTH_USER_MODEL, verbose_name='who approved the borrow'),
        ),
        migrations.AlterField(
            model_name='borrowlog',
            name='borrowdate',
            field=models.DateField(auto_now_add=True, verbose_name='time tool was checked out'),
        ),
    ]
