# Generated by Django 2.0.1 on 2018-01-31 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20180131_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlog',
            name='approvedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_log', to=settings.AUTH_USER_MODEL, verbose_name='who approved the borrow'),
        ),
    ]
