# Generated by Django 2.0.1 on 2018-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20180131_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsn',
            name='checkdate',
            field=models.DateTimeField(auto_now=True, null='True', verbose_name='time when tool was checked'),
        ),
    ]
