# Generated by Django 2.0.1 on 2018-02-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20180201_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tool name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='num',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='tool no.'),
        ),
    ]
