# Generated by Django 2.0.1 on 2018-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20180201_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='pmneeded',
            field=models.BooleanField(default=False, help_text='Will this tool have PM checks done?'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='tool name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='num',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='tool no.'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='pm',
            field=models.BooleanField(default=False, help_text='Is PM complete for this tool?'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='repair',
            field=models.BooleanField(default=False, help_text='Does this tool need to be repaired?'),
        ),
    ]
