# Generated by Django 2.0.1 on 2018-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20180208_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(default='-', max_length=200, verbose_name='tool name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='num',
            field=models.CharField(default='-', max_length=100, unique=True, verbose_name='tool no.'),
        ),
    ]
