# Generated by Django 2.0.1 on 2018-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20180208_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='pmneeded',
            field=models.BooleanField(default=False, help_text='Will this tool have PM checks done?', verbose_name='PM checks required'),
        ),
        migrations.AlterField(
            model_name='toolsn',
            name='pm',
            field=models.NullBooleanField(default=False, help_text='Is PM complete for this tool?'),
        ),
    ]
