# Generated by Django 2.0.1 on 2018-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20180208_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsn',
            name='pm',
            field=models.NullBooleanField(help_text='Is PM complete for this tool?'),
        ),
    ]
